- lib/tasks/db.js
Resolves #71 
IMPORTANT NOTE:
I tested this with some postgres URLs locally but there might be cases where either:
1. Some task (that I don't use) in sequelize is relying on some old behavior 
2. Someone else might use a database url that is not handled by this change
So: someone who knows the internals of sequelize and the cli a lot better than I do should review this.
I didn't see any existing tests for this so I didn't write any new ones.
> Use node url module to parse db url

- CHANGELOG.md
- lib/tasks/db.js
- test/db/migrate/old_schema.test.js
- test/support/helpers.js
> Auto migrate from old schema by checking autoMigrateOldSchema option

- lib/tasks/db.js
If the file names in the migration did not contain a timestamp (either no timestamp or timestamp not terminated by a dash). Simply added a check on the result of filename.match, if it's null it's assumed not to be a migration. Otherwise all is apples.
Tested on my own projects, however I haven't run it against the unit tests as there doesn't seem to be tests for the eloquently named `tryToMigrateFromOldScheme` function.
> Fixes issue where `tryToMigrateFromOldScheme` function was crashing mysteriously.

- .travis.yml
- CHANGELOG.md
- bin/get-env-matrix
- lib/tasks/db.js
- package.json
- test/db/migrate/old_schema.test.js
This PR
- is a follow-up of #99 
- fixes new default for `sequelize.query` in 2.0.0
- adds builds for sequelize @ 1.7.10, 2.0.0-rc8 and 2.0.0 final
> Follow-up of #99

- bin/sequelize
The fallback to resolve gulp below current path did not work on windows because unix shell script was executed instead of gulp.js
> Fixed second try to resolve path to gulp

- README.md
- lib/helpers/umzug-helper.js
- lib/tasks/db.js
- test/db/migrate-json.test.js
Please refer to Feature Request #101.
~~This commit introduces options `--storage` and `--storage-path` to tell Umzug to use JSON storage instead of MySQL table SequelizeMeta.~~
This commit introduces configuration options options `migrationStorage` and `migrationStoragePath` to tell Umzug to use JSON storage instead of MySQL table SequelizeMeta.
> Add option for JSON storage

- lib/assets/models/index.js
This accounts for the situation when there are non-JavaScript files in
the `models/` folder. If one is detected, we don't try to load it.
> Ensure model is JavaScript file. Fixes #131.

- lib/helpers/config-helper.js
Don't output password to CLI (for security).
> Mask password when outputting parsed URL

- bin/sequelize
This allows gulp to be installed somewhere up the tree
> Find gulp when installed somewhere in the tree

- bin/sequelize
- test/options.test.js
- test/support/helpers.js
Previously CLI calls would fail when an option was passed that was also
part of the config file or the options file.
Fixes https://github.com/sequelize/cli/issues/42
> Fix duplicate CLI args

- lib/helpers/config-helper.js
I noticed a deprecation warning from the Sequelize library, resulting from setting the logging config in the Sequelise-cli option to true: 
https://github.com/sequelize/sequelize/commit/00399231d04ef617bdfb29826c4de3097f5bf553
As your code uses console.log elsewhere, this just compliments that (assuming similar semantics for the logging option as it is passed in)
Although, could so something more elaborate with converting a string to the function eg.
```javascript
if (_.isString(this.config.logging)) {
var funcPath = this.config.logging.split(".");
var func = global;
while (funcPath[0] && func) { func = func[funcPath[0]]; funcPath.shift(); }
this.config.logging = (_.isFunction(func))? func : false;
}
```
using the config option:
```json
...
logging: "console.log"
...
```
> Change logging config to console.log function when set

- lib/tasks/db.js
There's a test for dialectOptions but when options are loaded from config file, dialectOptions get ignored. In order to create ssl connection to ssl enabled endpoints, we need to pass dialectOptions to mysql driver.
> Add options for dialectOptions

- CHANGELOG.md
- README.md
- lib/helpers/umzug-helper.js
- lib/tasks/db.js
- package.json
- test/db/seed.test.js
- test/db/seed/all.test.js
- test/db/seed/undo.test.js
- test/db/seed/undo/all.test.js
- test/support/helpers.js
* it now defaults to no storage (does not store tasks run)
* this can be changed with configurations
* db:seed and db:seed:undo now require an option '--seed' with the file to seed or unseed (multiple '--seed' options work)
* new db:seed:all command that runs all seeds available in the seeder directory
* db:seed:undo:all runs the down function for all seeds available in the seed directory
> Fixed seeder to behave as a seeder should

- README.md
- gulpfile.js
- package.json
This changes the highlighting language of the examples with comments from JSON to JavaScript, because JSON does not allow comments and results in the following ugly highlighting artifacts:
> Prevent ugly comments highlighting

- lib/tasks/db.js
For now, the process exits correctly when there is an error.
> Catch error for db:migrate:undo[:all]

- README.md
Library is great, but more usage examples are need for a lower barrier to entry.
> Example usage of raw sql in migration

- lib/assets/models/model.js
- lib/helpers/model-helper.js
- test/model/create.test.js
When creating a model with the `--underscored` flag, the option `underscored: true` was not added to the generated model file. 
Added a corresponding test case.
When the flag is not present, the model file is generated the same way it was before.
> Add underscored option to generated model when created with --underscored

- lib/tasks/db.js
- test/db/migrate/status.test.js
This also addresses #165 , with a slightly different approach from #379.
Both `db:migrate:status` and `db:migrate:pending` would probably be useful.
> add db:migrate:status

- lib/helpers/config-helper.js
- lib/helpers/gulp-helper.js
- lib/helpers/version-helper.js
- lib/tasks/model.js
- test/db/migrate.test.js
- test/db/seed.test.js
Google Cloud's infrastructure doesn't inject metadata into the environment, instead, you have to call an outside service. Because of this, I need a migration solution that offers asynchronous configuration.
This, as I've discovered over the past five hours, is surprisingly difficult primarily because of a combination of:
1. Gulp doesn't support async configuration and doesn't plan to add it, [see Gulp Issue 1505](https://github.com/gulpjs/gulp/issues/1505)
2. The config helper API relies on state that is internal to the module and all calls assume the initialization of that state is synchronous.
To maintain existing behavior, this change takes care to initialize config at the start of all gulp tasks but waits until readConfig is called before logging anything or showing errors.
I'm happy …
> Add async configuration support.

- lib/tasks/db.js
I was building seeders for a new project and found that the error message printed did not include enough information (like which file caused the problem).  This PR enhances the error message printed in the .catch(function(e) { }) handlers so include the stack trace.  As an example, an exception running db:seed:undo now looks like the following, and I can know exactly where the error is.
== 20170110190423-admin-act: reverting =======
Seed file failed with error: Cannot read property 'getProfile' of null TypeError: Cannot read property 'getProfile' of null
at Model.<anonymous> (/usr/src/app/server/db/seeders/20170110190423-admin-act.js:36:24)
at Model.tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler …
> include stack trace when printing error message if a seeder fails

- lib/tasks/db.js
- test/db/seed/undo/all.test.js
Check for `pending` seeds when seeder storage is 'none', otherwise check for `executed` seeds. Tests included
Closes https://github.com/sequelize/cli/pull/253
Closes https://github.com/sequelize/cli/pull/391
Closes https://github.com/sequelize/cli/pull/421
Fixes https://github.com/sequelize/cli/issues/252
Fixes https://github.com/sequelize/cli/issues/408
Fixes https://github.com/sequelize/cli/issues/403
Fixes https://github.com/sequelize/cli/issues/308
> Fix seed:undo:all issue

- lib/tasks/db.js
- test/db/migrate/undo.test.js
Solves https://github.com/sequelize/cli/issues/350
@bcaudan @theartoflogic
> add support for named db:migrate:undo

- README.md
- lib/tasks/db.js
- test/db/migrate/schema/add_timestamps.test.js
This PR adds the client option to upgrade `SequelizeMeta` to have `timestamps` enabled.
Also some minor updates to `README`.
> Add schema change to add timestamps to Sequelize meta table

- lib/tasks/db.js
- test/db/migrate/undo/all_to.test.js
- test/support/assets/migrations/20170526153000-createPost.js
Add option to undo migrations to the specific version.
https://github.com/sequelize/umzug#reverting-executed-migration
This option is very useful when continuous integration is used, since it allows easier rolling back in case something went wrong.
> Add option to db:migrate:undo:all which allows reverting migration to a specific version.

- lib/helpers/config-helper.js
- lib/tasks/db.js
We are already parsing config file options in `config-helper.js` and we should keep this all in the same place. This PR moves the `use_env_variable` to `config-helper.js` and removes all the extra logic from `tasks/db.js`.
Also fixed the database and ssl parameters, so an url string with `...?ssl=true` does not break anymore.
> Improve sequelize options handling

- FAQ.md
- README.md
Command to create a new migration
> migration command

- src/core/yargs.js
- src/helpers/config-helper.js
- src/helpers/generic-helper.js
- src/helpers/path-helper.js
- src/sequelize.js
- test/db/migrate.test.js
- test/options.test.js
Closes https://github.com/sequelize/cli/issues/536
Older helpers were still directly loading `yargs` which was not configured to read `.sequelizerc` file. Now a single `yargs` instance in used to fix this issue. Added tests to prevent regressions.
> fix(.sequelizerc): options files is not used by all commands

- src/helpers/config-helper.js
Uses `process.env` variables to control config for production (as [documented](http://docs.sequelizejs.com/manual/tutorial/migrations.html)).
Details in commits.
> Improved database defaults

- src/commands/migrate.js
- test/db/migrate.test.js
Enables underlying umzug functionality
> Added --from and --to support for db:migrate

- src/assets/migrations/create-table.js
- src/assets/models/model.js
- src/helpers/model-helper.js
- test/model/create.test.js
for https://github.com/sequelize/cli/issues/155
> Feature: specify array type with model:create

- CHANGELOG.md
- package.json
- test/model/create.test.js
Created this to deal with a merge conflict so it can be merged. Preserved commits for contribution credit.
> Model association for sequalize-cli 4.0.0 updates

- src/assets/models/model.js
When running the `model:generate` command, it generates files and uses `var` for the model definition.
I changed it so that it uses the better keyword `const`.
> Use const for model definition

- src/commands/model_generate.js
Currently if model:create tries to recreate the migration and model
files for the same name, the user is asked to use the --force flag which
does not currently work as it is not being accepted currently. This
allows --force with value true
Fixes #638
> Adds in force flag for model:create

- src/commands/model_generate.js
- src/helpers/model-helper.js
- test/model/create.test.js
- test/support/helpers.js
I ran into a small problem today when generating some models, it's pretty easy to mistakenly write something like 'someDate:datetime' as an attribute when it is just 'someDate:date'. The generate command lets it slide and then you end up with some [hard to debug .toString() errors](https://stackoverflow.com/questions/46034605/sequelize-cannot-read-property-tostring-of-undefined) by when migrating.
I've added an error condition which halts the generation if any of the attributes contain an invalid DataType.
Also, I noticed that `runCli()` in `test/support/helpers.js` wasn't correctly asserting a non-zero error code so I fixed it by not passing through result.
> Add model:generate attribute datatype validation

- src/commands/model_generate.js
Make the "--force" a real flag that does not require anything after it. Fix #690
```javascipt
if (!args.force && helpers.model.modelFileExists(modelPath)) {
```
make the `sequelize ... --force` useless because `args.force` is a `''` which yields `!args.force` to be `true`. And the system will ask the user to add `--force` again. That's what I encountered in #690.
In a nutshell, we need to add something after the `--force` to make it work **in this old situation**.
```javascript
if (args.force === undefined && helpers.model.modelFileExists(modelPath)) {
```
so when the user adds `--force`, the `args.force` is not `undefined`, so everything is OK.
I compiled it and run `npm test` and it passed.
> Make the `--force` a real flag

- docker-compose.yml
- src/commands/database.js
- test/db/db-create.test.js
same as #699 
But it's a patch with `sequelize@4`. No `create/dropDatabase` used.
resolved #698
resolved #590
resolved #629
> feat(db:create): support options on db:create with sequelize@4

- docs/FAQ.md
- src/assets/migrations/create-table.js
- src/assets/models/model.js
- src/helpers/model-helper.js
- test/model/create.test.js
Add support for `model:generate --name User role:enum:{Admin, Guest}`
Closes #550
> feat(mode:generate) add enum support

- src/commands/database.js
- src/commands/init.js
- src/commands/migrate.js
- src/commands/migrate_undo.js
- src/commands/migrate_undo_all.js
- src/commands/migration_generate.js
- src/commands/model_generate.js
- src/commands/seed.js
- src/commands/seed_generate.js
- src/commands/seed_one.js
- src/core/yargs.js
- src/sequelize.js
Fixes https://github.com/sequelize/cli/issues/707
When `--help` or `version` are provided, yargs exit the process before loading the commands and the view helper.
Output with `--help`:
```
Options:
--help     Show help                                                 [boolean]
--version  Show version number                            [boolean]
```
Output with `--version`:
```
5.3.0
```
Add [exitProcess(false)](https://github.com/yargs/yargs/blob/master/docs/api.md#exitprocessenable) so the process doesn't exit before loading the commands. In addition, `help` and `version` are also disable so they don't get printed when loading yargs.
`help` and `version` are enabled when loading the modules. 
Output with `--help`:
```
Sequelize CLI [Node: 10.13.0, CLI: 5.3.0, ORM: 4.41.0]
sequelize …
```
> fix: show commands with --help

- docs/FAQ.md
Enum type brackets need to be quoted or escaped in most shells.
* Update documenation and add an addition FAQ item about issue
> Documentation: Update docs for enum type

- src/helpers/config-helper.js
As mentioned [here](https://github.com/sequelize/sequelize/issues/8417#issuecomment-454631401) and [here](https://github.com/sequelize/sequelize/issues/8417#issuecomment-337884136) following the CLI docs with default settings prompts a deprecation warning.
@SystemDisc clearly defines solution [here](https://github.com/sequelize/sequelize/issues/8417#issuecomment-461150731). So I suggest adding this into the default CLI config to avoid confusion and improve security when using migrations.
This seems like the most straightforward solution to me but if a change is better suited in the docs happy to contribute there instead.
Thanks
> Update default config (sequelize#8417)

- src/helpers/config-helper.js
https://github.com/sequelize/cli/issues/172 is still happening when special characters find their way in a password
> Bug Fix: Special characters in password are not escaped

- package.json
The binary is currently called sequelize, but references in documentation say it is sequelize-cli
The result is npx always ends up trying to download sequelize-cli from npm. This is because npx looks for the command in the path and then checks npm if it fails to find it. To show this, run `npx --no-install sequelize-cli --help` which will prevent npx from falling back to downloading the package from npm. This command should fail without this change.
This should greatly increase performance for people following the docs as well as prevent issues such as #803 .
Rather than delete the existing binary name of sequelize, I figured it was best to add sequelize-cli as a secondary name in case other people had figured this out and rely on using the name sequelize in scripts or commands (and the …
> Added sequelize-cli as an alias for the binary

- src/core/migrator.js
- test/db/migrate.test.js
- test/support/assets/migrations/cjs/20200617063700-createComment.cjs
we are using ESM and this minimally supports a migration file with a cjs extension. 
Having this allows us to use sequelize and commonJS-based migrations within a module-enabled application.
> support a migration with a cjs extension

- package.json
If one wants to vendor a forked version of the module, they can't run the `bin` scripts because the package hasn't transpiled. 
Adding a `prepare` script will address that.
> add prepare script for git-based vendoring

- src/sequelize.js
The `command-recommendation` feature comes in handy if the user mistypes a command.
> feat: recommend matching commands

- src/core/migrator.js
- src/helpers/umzug-helper.js
- test/db/migrate/schema/add_timestamps.test.js
The relevant fields are: `seedersTimestamps` and `migrationTimestamps` which can be set in the sequelize `config.json`
The code will also autodetect if the table already has the timestamps and will act upon it.
> Add support for timestamps in migration tables

- src/core/migrator.js
- test/db/migrate.test.js
- test/support/assets/migrations/ts/20200705000000-createTypescript.ts
> Support migrations files with ts file extension

- src/core/migrator.js
- test/db/migrate.test.js
- test/support/assets/migrations/ts/20200817171700-createTypescriptDS.d.ts
Changed the migrator pattern to not match `.d.ts` files.
[Here's](https://regexr.com/5abb5) the regexr playground for seeing the new pattern in action
[Here's](https://stackoverflow.com/questions/43490499/webpack-regex-test-that-matches-ts-but-not-d-ts) the source where I got the pattern
Current workaround I use is to run `rimraf dist/migrations/*.d.ts` before running migrations.
> Update migrator pattern to not match .d.ts files 

- README.md
The CI badge on the README is pointing to `master` when it should be pointing to `main`.
> Update CI badge branch to main

- .mocharc.yaml
- package.json
- scripts/mocha-bootload.js
In some of the Node 16 tests for #974 it seemed that mocha was not on a timeout of 30000 but on the default 2000. Not sure why but by moving it to a separate config file it works [fine](https://github.com/WikiRik/cli/actions/runs/1435493979). The config can also be a part of package.json as a mocha property but I prefer to move it to its own config file.
Reporter spec was removed since it is the [default](https://mochajs.org/#-reporter-name-r-name).
I also removed the script, since it only required one thing so it can also be a part of the config file. As per; https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml
> meta(mocha): move mocha config to own file

- src/commands/seed_one.js
fixed #943 
The `npm run test` has 2 faileds.
First one is on prettier (in file `test/support/helpers.js`), but I didn't change this file.
Second one is on `1) [SQLITE] lib/sequelize model:create` -> `attributes` -> `--attributes first_name:string,last_name:string,bio:text,role:enum:{Admin,"Guest User"},reviews:array:text
exits with exit code 0:`, but this test case also failed in master branch.
I think those test failed is not about my changes.
> fix: running single seeder is so slow

- package.json
Yeah, so in https://github.com/sequelize/cli/pull/972 we didn't notice that it didn't actually add the config for semantic-release. But now it should hopefully work, this is just a copy from the core repo
> build: add semantic-release config

- src/helpers/import-helper.js
https://github.com/sequelize/cli/pull/987 introduced a bug that caused sequelize-cli to be unusable on windows, as it tries to import the config file using `import()` instead of `require()`. Unlike `require`, `import` expects the path to be a valid URL.
Closes https://github.com/sequelize/cli/issues/994
> fix: fix config import breaking on windows

- .github/workflows/codeql-analysis.yml
This PR adds [CodeQL analysis](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql). Config file was generated automatically, but I did remove that it runs on all pushes to main and on a schedule since running it with every PR to main is enough in my opinion.
> build: add codeql analysis

- renovate.json
config:base detects if the repo is an app or a library. For the main repo it's obviously a library and for CLI it detected this as an app. This change makes sure that we use the library config. As per; https://docs.renovatebot.com/presets-config/#configjs-lib
> build: only pin devDependencies

- .github/workflows/codeql-analysis.yml
I was hoping that the results would pop up in the Security tab by default but it doesn't since it only checks the branches of the PRs. And apparently, it will fail every PR because it can't find the initial results of the base branch (main) which is not something we want.
So this should solve all of that.
> build: add codeql to main pushes

- package.json
- src/assets/migrations/create-table.js
- src/assets/migrations/skeleton.js
- src/assets/seeders/skeleton.js
- types.d.ts
Problem: No IntelliSense when working on migration files
Solution: Add a type definition file and use `/** @type */` tag to make editors infer the type of each variable.
> feat(types): Improve IntelliSense when generating migration files

- src/helpers/view-helper.js
close https://github.com/sequelize/cli/issues/1138
This PR adds additional error output.  Currently the error output may be insufficient to hone in on the problem.
https://www.postgresql.org/docs/current/plpgsql-errors-and-messages.html
```
ERROR: SequelizeForeignKeyConstraintError: insert or update on table "my_table" violates foreign key constraint "...."
ERROR DETAIL: Key (my_column)=(1) is not present in table "my_table"
```
Behind a debug flag.  My initial hunch is to consider this a helpful feature that users get out of the box.  Happy to put behind a debug flag though!
> feat: add ERROR detail to output of migration

- src/assets/models/index.js
The models/index.js file is an auto-generated file used to automatically register all models from the models folder
It works under the assumption that the only files you have in your /models folder are models.
This works for most of the cases, but it causes an issue for projects using tests colocated with the tested file, e.g.
```
models/
person.js
person.test.js
dog.js
dog.test.js
index.js
```
for such cases, if you want to add unit tests, you would have to either move to a symmetric /tests folder that replicates the structure of your project (for example as this project does), or follow this approach only for the models folder (quite inconsistent), or not write tests for models (quite bad)
This PR addresses the issue by adding a …
> feat: add support for test files colocated with models

- src/helpers/view-helper.js
Using `"sequelize-cli": "6.5.2",`
When `up` handler of a migration throws a custom error.
```js
throw new Error(
`foobar`,
);
```
The cli throws the following error
```bash
TypeError: Cannot read properties of undefined (reading 'detail')
at Object.error (/myproject/node_modules/sequelize-cli/lib/helpers/view-helper.js:31:24)
at /myproject/node_modules/sequelize-cli/lib/commands/migrate.js:68:39
at async exports.handler (/myproject/node_modules/sequelize-cli/lib/commands/migrate.js:27:7)
```
The error originates from this line:
```js
if (error.original.detail) { // this causes the error because original is null/undefined
console.error(`${_cliColor.default.red('ERROR DETAIL:')} ${error.original.detail}`);
}
```
In this PR we change …
> fix: only show error detail when error.original is defined

- docs/FAQ.md
For me none of the suggestions in [stackoverflow](https://stackoverflow.com/questions/62275266/not-able-to-create-enum-type-attribute-using-sequelize-cli) or [FAQ](https://github.com/sequelize/cli/blob/1a7f8a546e39d7ddd8a9c3d9640086e481982bf0/docs/FAQ.md) works for enum model create.
I found out that the enum list works only if I have a space after the comma.
In this PR we add a working way to use enum type in the FAQ for model create.
Tested on M1 mac vscode terminal (zsh).
> Document working model create command

- .github/workflows/ci.yml
- docker-compose.yml
- yarn.lock
- Use docker compose instead of docker-compose due to a newer version of docker on ubuntu-latest runners.
- Use jwilder/dockerize instead of giorgos/takis to wait for the db to run in the CI process due to an old image format.
- Format the docker compose command for postgres because it was failing to set locale.gen file
Upon seeing the following PR the would benefit an issue I'm dealing with  https://github.com/sequelize/cli/pull/1532 I noticed the CI is broken and trying to fix it.
> ci: update docker compose and wait for db image

- .github/workflows/ci.yml
- package.json
- src/commands/database.js
- src/commands/migration_generate.js
- src/commands/model_generate.js
- src/commands/seed_generate.js
- src/helpers/view-helper.js
- yarn.lock
`cli-color` -> `es5-ext` detected as a virus
https://github.com/medikoo/es5-ext/issues/186
And `picocolors` has much lighter weight, no dependencies.
> refactor: replace `cli-color` with `picocolors`

- src/helpers/path-helper.js
- Replace `fs.R_OK` with `fs.constants.R_OK` since it got deprecated in node 24
- https://nodejs.org/en/blog/release/v24.0.0
- [b02cd411c2](https://github.com/nodejs/node/commit/b02cd411c2) - (SEMVER-MAJOR) fs: runtime deprecate fs.F_OK, fs.R_OK, fs.W_OK, fs.X_OK (Livia Medeiros) [#49686](https://github.com/nodejs/node/pull/49686)
- https://github.com/nodejs/node/pull/49683
> fix: replace fs.R_OK with fs.constants.R_OK
