.jshintrc
lib/helpers/gulp-helper.js
lib/tasks/db.js
test/support/helpers.js
test/support/index.js

Use proper promise functions

---

README.md
bin/sequelize

--harmony enables all features, so I prefer to enable just what I need - generators

allow using specific harmony flags

---

.travis.yml
lib/helpers/template-helper.js
package.json

Add compatibility with js2coffee 2.0

---

lib/tasks/db.js

see https://github.com/sequelize/cli/issues/92

improved logging message when schema is up to date

---

README.md
lib/helpers/gulp-helper.js

I was perusing the code and noticed the --url command line option. It is very useful for my use cases and I thought documenting it might be valued. I have only used it for a few commands thus far, but it is proving useful.
Thoughts?

Document hidden --url property

---

lib/assets/models/index.js

[Changed] Fix check of associate method

---

lib/tasks/db.js
test/db/migrate.test.js
test/support/assets/migrations/invalid/20141208213500-createPerson.coffee
test/support/assets/migrations/invalid/20141208213500-createPerson.js

Fixes https://github.com/sequelize/cli/issues/110

Return exit code 1 when migrations failed

---

lib/assets/models/index.js

See issue #168 for more details

add easy support for environment connection string

---

lib/helpers/generic-helper.js

Tested on ubuntu 14.04 with node 0.10.25 (installed globally in /usr/local/lib/node_modules) and 0.12.7 (installed globally in a nodeenv)

Use node's resolve resolution. Fixes #104

---

lib/helpers/generic-helper.js

Try to load sequelize first via the native require.resolve and then
with the node-resolve module.

[Changed] Cascade package resolution

---

lib/assets/seeders/skeleton.js

Fixes https://github.com/sequelize/cli/pull/176#issuecomment-137620739

[Changed] Add options object to seed template

---

bin/sequelize
test/options.test.js

[Changed] Make options path process relative

---

bin/sequelize
lib/helpers/config-helper.js
lib/helpers/init-helper.js
lib/helpers/model-helper.js
lib/helpers/path-helper.js
lib/tasks/model.js
test/db/migrate.test.js

This PR makes the CLI read the configuration from `config/config.js` if available. This way it is possible to have dynamic content in the configuration file (e.g. you could read environment variables).

[Added] Read configuration from config.js if available

---

lib/assets/migrations/create-table.js
lib/helpers/migration-helper.js
lib/tasks/migration.js
lib/tasks/model.js
test/model/create.test.js

Needed a break from thinking, this feature was simple to do, so I just did it.

--underscore to create migrations with 'created_at' and 'updated_at'

---

.gitignore
README.md
lib/helpers/config-helper.js
test/db/migrate.test.js
var/vagrant/README.md
var/vagrant/Vagrantfile
var/vagrant/provision.sh

Please, review.
Besides, I have added the Vagrant definition and provision, in order to be able to setup mysql server quickly.
Regards,

url as option; custom logging function 

---

lib/assets/models/index.js

Gain a tiny advantage of by doing all filtering at the same time, since the code is run synchronously.

Filtering everything onf the go

---

lib/assets/models/index.js

[Fixed] Filtering of js files in models/index.js

---

lib/tasks/db.js
test/db/migrate/old_schema.test.js
test/support/helpers.js
test/support/index.js

Fixes #247 
I added `return` to some parts in Promise handler. I modified to return `null` when handler not require return value. Reason of return null  is written in following.
http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it

Fix promise warning

---

package.json

Upgrade gulp to 3.9.1
issue #267

Upgrade gulp

---

lib/helpers/path-helper.js

create UTC dates for migration and seed filenames

---

lib/tasks/db.js

- fixes sequelize/cli/issues/242
- fixes sequelize/cli/issues/247

fixes Bluebird promise warnings

---

lib/tasks/db.js

this is the same fix (`var` was used instead of `const` because I couldn't determine the minimum support nodJS version) as the following [merged] PR for sequelize itself:
> https://github.com/sequelize/sequelize/pull/6348

make it possible to use ":" in passwords in a DSN

---

.travis.yml
test/support/helpers.js

Lean Build

---

package.json

chore(package): update yargs to version 6.2.0

---

package.json

chore(package): update sqlite3 to version 3.1.8

---

lib/tasks/init.js

containts -> contains

---

FAQ.md

Added new FAQ

---

README.md

add trailing commas to json config, fix display error.

add trailing commas to json

---

docker-compose.yml
src/commands/database.js
src/core/migrator.js
src/sequelize.js
test/db/db-create.test.js
test/db/db-drop.test.js
test/support/index.js

Closes https://github.com/sequelize/cli/issues/70
Closes https://github.com/sequelize/cli/pull/510

added: db:create / db:drop tasks

---

src/helpers/config-helper.js

Revert "Improved database defaults"

---

docs/README.md

Add document for --options-path

docs: options-path

---

src/helpers/model-helper.js

fix: sequelize directly imported

---

src/helpers/init-helper.js

Relating to the issue discussed in https://github.com/sequelize/cli/issues/614
I figured I should try and resolve this.

Fixed config path issue in index.js for windows upon init

---

src/commands/database.js

fix(db:create): syntax errors on mssql create statement

---

src/helpers/version-helper.js

Add 'postgresql' protocol for getDialectName method.

Add support 'postgresql' protocol.

---

src/commands/database.js

Prevent error on db:drop if database does not exist

---

.travis.yml
README.md
package.json
src/commands/database.js
src/core/migrator.js
test/db/db-create.test.js
test/db/migrate/schema/add_timestamps.test.js
test/support/helpers.js
test/support/index.js

docs: update for v6

---

docs/README.md

Fixes minor formatting typo in documentation

---

src/commands/seed.js
src/core/migrator.js
test/support/helpers.js

Closes #967 with caveat that no intentful change to linting rules has triggered these lint failures

fix: lint errors #967

---

CHANGELOG.md

fix CHANGELOG v6.1.0 issue link error

docs: fix CHANGELOG.md

---

src/assets/models/model.js

style: remove unnecessary semicolon

---

src/assets/migrations/create-table.js
src/assets/migrations/skeleton.js
src/assets/seeders/skeleton.js
test/migration/create.test.js
test/seed/create.test.js

Use shorthand functions in migration files, for a modern nicer syntax.

Use shorthand functions in migration files

---

src/commands/migrate.js
test/db/migrate.test.js

Closes #860, closes #1028
feat: run specific migration file with `--name` option
Example:
```sh
npx sequelize db:migrate --name 20111117063700-createPerson
```

feat: run specific migration file with --name option

---

renovate.json

Unifies the Renovate config with the one from the main repo

build(renovate): unify config with main repo

---

package.json

Close #1183.
Build package locally with `npm pack`, then test with VS Code.\
Types were probably hinted.

fix(types): add type declarations to package

---

.github/workflows/ci.yml

Otherwise semantic-release will not work and we can't do a new release, see https://github.com/sequelize/cli/actions/runs/4004648302/jobs/6874501231

meta: update release Node version to 18

---

package.json
yarn.lock

This is done so lockfile maintenance can happen again, see #1288 for the reasoning

meta: pin mysql2 to 3.2.0

---

src/helpers/config-helper.js

Uses code from the main repo; https://github.com/sequelize/sequelize/blob/b3f03aed681abe0d5e22a9628b083f59f6772305/packages/core/src/utils/url.ts#L37-L43
Fixes #1388

fix: allow : to be used in password

---

package.json
yarn.lock

chore(deps): pin js-beautify because of breaking change in patch
